Vagrant.configure("2") do |config|
	config.vm.box = "bento/ubuntu-20.04"
	config.vm.provider "virtualbox" do |v|
		v.memory = 4096
		v.cpus = 4
		v.name = "DevOps"
	end
	config.vm.network "forwarded_port", guest: 19999, host: 19999
	config.vm.network "forwarded_port", guest: 9090, host: 9090
	config.vm.network "forwarded_port", guest: 9100, host: 9100
end
 
